config/routes.rb
Tag::Application.routes.draw do
  get "welcome/1"
  get "welcome/2"
  get "welcome/3"
  get "welcome/4"
  get "welcome/5"
  get "welcome/6"
  get "welcome/7"
  get "welcome/8"
  get "welcome/9"
  get "welcome/10"
  get "welcome/11"
  get "welcome/12"
  get "welcome/studash"
  get "welcome/studash2"

  get "welcome/contact"

  resources :user_game_preferences

  resources :games

  resources :user_funs

  match "/funs/home" => "funs#home" 
  match "/funs/fun_list" => "funs#fun_list" 
  match "/funs/my_fun_list" => "funs#my_fun_list" 
  resources :funs

  resources :music_likes

  match "/musics/music_list" => "musics#music_list"
  resources :musics

  match "/sport_levels/sport_level_list" => "sport_levels#sport_level_list"
  match "/sport_levels/home" => "sport_levels#home"
  match "/sport_levels/guidence" => "sport_levels#guidence"
  match "/sport_levels/video" => "sport_levels#video"
  resources :sport_levels

  resources :scaffolds

  get "/home" => "admin#home"
  get "/tools" => "admin#tools"

  resources :user_sport_preferences

  resources :pe_classmembers

  match "/class" => "pe_classes#home"
  match "/class/news" => "pe_classes#news_list"
  resources :pe_classes

  resources :schools

  resources :teammembers

  match "/teams/home" => "teams#home"
  match "/teams/team_information" => "teams#team_information"
  match "/teams/teamowner_information" => "teams#teamowner_information"
  match "/teams/team_information_list" => "teams#team_information_list"
  match "/teams/score_list" => "teams#score_list"
  resources :teams

  resources :sports

  match "/trainers/home" => "trainers#home"  
  resources :trainers 

  match "/teachers/home" => "teachers#home" 
  match "/teachers/class_list" => "teachers#class_list" 
  match "/teachers/student_list" => "teachers#student_list" 
  match "/teachers/student_information" => "teachers#student_information" 
  match "/teachers/event_list" => "teachers#event_list" 
  resources :teachers

  match "/events/datetime_list" => "events#datetime_list"
  match "/events/event_information" => "events#event_information"
  match "/events/my_event_information" => "events#my_event_information"
  resources :events

  match "/locations/location_list" => "locations#location_list"
  resources :locations

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy

    get 'login_teacher' => :new_teacher
    post 'login_teacher' => :create_teacher
    delete 'logout_teacher' => :destroy_teacher
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :sessions

  match "/users/confirm_information" => "users#confirm_information"
  match "/users/confirm_parental_consent" => "users#confirm_parental_consent"
  match "/users/render_confirm_parental_consent" => "users#render_confirm_parental_consent"
  match "/users/render_reset_password" => "users#render_reset_password"
  match "/users/reset_password" => "users#reset_password"
  resources :users

  root :to => 'welcome#index'

end

app/models/user_fun.rb
class UserFun < ActiveRecord::Base
  # attr_accessible
  attr_accessible :fun_id, :user_id
 
  # dependencies
  belongs_to :fun
  belongs_to :user

  # functions
  # find_by_user1(user_id)
  #   INPUT: user_id (value)
  #   OUTPUT: user_funs (UserFun.object)
  #   FROM: models/pe_class/find_news
  #   2012.7.5 Yueying
  def self.find_by_user1(user_id)
    user = User.find(user_id)
    pe_class_id = user.pe_class_id
    user_fun_ids = UserFun.find_by_sql("SELECT user_funs.id FROM users, user_funs WHERE users.pe_class_id = " + pe_class_id.to_s + " AND users.id = user_funs.user_id")
    return user_funs = UserFun.find_all_by_id(user_fun_ids)
  end
end

app/controllers/user_funs_controller.rb
class UserFunsController < ApplicationController
  # GET /user_funs
  # GET /user_funs.json
  def index
    @user_funs = UserFun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @user_funs }
    end
  end

  # GET /user_funs/1
  # GET /user_funs/1.json
  def show
    @user_fun = UserFun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user_fun }
    end
  end

  # GET /user_funs/new
  # GET /user_funs/new.json
  def new
    @user_fun = UserFun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user_fun }
    end
  end

  # GET /user_funs/1/edit
  def edit
    @user_fun = UserFun.find(params[:id])
  end

  # POST /user_funs
  # POST /user_funs.json
  #   INPUT: fun_id (value)
  #   OUTPUT: SAVE user_fun (UserFun.object), fun.popularity +1
  #   FROM: views/funs/list_selected
  #   TO: 
  #   2012.7.6 Yueying
  def create
    hash = params[:register]

    if  hash != nil
      user_fun = UserFun.new
      user_fun.user_id = session[:user_id]
      hash_invert = hash.invert
      user_fun.fun_id = hash_invert.values_at("register").first.to_i
      user_fun.save

      fun = user_fun.fun
      sql = ActiveRecord::Base.connection()
      sql.execute("UPDATE funs SET funs.popularity = funs.popularity + 1 WHERE funs.id = " + fun.id.to_s)
    end

    respond_to do |format|
      format.html { redirect_to '/admin/home' }
    end
  end

  # PUT /user_funs/1
  # PUT /user_funs/1.json
  def update
    @user_fun = UserFun.find(params[:id])

    respond_to do |format|
      if @user_fun.update_attributes(params[:user_fun])
        format.html { redirect_to @user_fun, :notice => 'User fun was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user_fun.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_funs/1
  # DELETE /user_funs/1.json
  def destroy
    @user_fun = UserFun.find(params[:id])
    @user_fun.destroy

    respond_to do |format|
      format.html { redirect_to user_funs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_funs_helper.rb
module UserFunsHelper
end

app/views/user_funs/_form.html.erb
<%= form_for(@user_fun) do |f| %>
  <% if @user_fun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_fun.errors.count, "error") %> prohibited this user_fun from being saved:</h2>

      <ul>
      <% @user_fun.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :fun_id %><br />
    <%= f.number_field :fun_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_funs/edit.html.erb
<h1>Editing user_fun</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_fun %> |
<%= link_to 'Back', user_funs_path %>

app/views/user_funs/index.html.erb
<h1>Listing user_funs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Fun</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_funs.each do |user_fun| %>
  <tr>
    <td><%= user_fun.user_id %></td>
    <td><%= user_fun.fun_id %></td>
    <td><%= link_to 'Show', user_fun %></td>
    <td><%= link_to 'Edit', edit_user_fun_path(user_fun) %></td>
    <td><%= link_to 'Destroy', user_fun, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User fun', new_user_fun_path %>

app/views/user_funs/new.html.erb
<h1>New user_fun</h1>

<%= render 'form' %>

<%= link_to 'Back', user_funs_path %>

app/views/user_funs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_fun.user_id %>
</p>

<p>
  <b>Fun:</b>
  <%= @user_fun.fun_id %>
</p>


<%= link_to 'Edit', edit_user_fun_path(@user_fun) %> |
<%= link_to 'Back', user_funs_path %>