config/routes.rb
Tag::Application.routes.draw do
  get "welcome/1"
  get "welcome/2"
  get "welcome/3"
  get "welcome/4"
  get "welcome/5"
  get "welcome/6"
  get "welcome/7"
  get "welcome/8"
  get "welcome/9"
  get "welcome/10"
  get "welcome/11"
  get "welcome/12"
  get "welcome/studash"
  get "welcome/studash2"

  get "welcome/contact"

  resources :user_game_preferences

  resources :games

  resources :user_funs

  match "/funs/home" => "funs#home" 
  match "/funs/fun_list" => "funs#fun_list" 
  match "/funs/my_fun_list" => "funs#my_fun_list" 
  resources :funs

  resources :music_likes

  match "/musics/music_list" => "musics#music_list"
  resources :musics

  match "/sport_levels/sport_level_list" => "sport_levels#sport_level_list"
  match "/sport_levels/home" => "sport_levels#home"
  match "/sport_levels/guidence" => "sport_levels#guidence"
  match "/sport_levels/video" => "sport_levels#video"
  resources :sport_levels

  resources :scaffolds

  get "/home" => "admin#home"
  get "/tools" => "admin#tools"

  resources :user_sport_preferences

  resources :pe_classmembers

  match "/class" => "pe_classes#home"
  match "/class/news" => "pe_classes#news_list"
  resources :pe_classes

  resources :schools

  resources :teammembers

  match "/teams/home" => "teams#home"
  match "/teams/team_information" => "teams#team_information"
  match "/teams/teamowner_information" => "teams#teamowner_information"
  match "/teams/team_information_list" => "teams#team_information_list"
  match "/teams/score_list" => "teams#score_list"
  resources :teams

  resources :sports

  match "/trainers/home" => "trainers#home"  
  resources :trainers 

  match "/teachers/home" => "teachers#home" 
  match "/teachers/class_list" => "teachers#class_list" 
  match "/teachers/student_list" => "teachers#student_list" 
  match "/teachers/student_information" => "teachers#student_information" 
  match "/teachers/event_list" => "teachers#event_list" 
  resources :teachers

  match "/events/datetime_list" => "events#datetime_list"
  match "/events/event_information" => "events#event_information"
  match "/events/my_event_information" => "events#my_event_information"
  resources :events

  match "/locations/location_list" => "locations#location_list"
  resources :locations

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy

    get 'login_teacher' => :new_teacher
    post 'login_teacher' => :create_teacher
    delete 'logout_teacher' => :destroy_teacher
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :sessions

  match "/users/confirm_information" => "users#confirm_information"
  match "/users/confirm_parental_consent" => "users#confirm_parental_consent"
  match "/users/render_confirm_parental_consent" => "users#render_confirm_parental_consent"
  match "/users/render_reset_password" => "users#render_reset_password"
  match "/users/reset_password" => "users#reset_password"
  resources :users

  root :to => 'welcome#index'

end

app/models/teammember.rb
class Teammember < ActiveRecord::Base
  # attr_accessible
  attr_accessible :team_id, :user_id

  # dependencies
  belongs_to :team
  belongs_to :user

  # functions

end

app/controllers/teammembers_controller.rb
class TeammembersController < ApplicationController
  # GET /teammembers
  # GET /teammembers.json
  def index
    @teammembers = Teammember.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @teammembers }
    end
  end

  # GET /teammembers/1
  # GET /teammembers/1.json
  def show
    @teammember = Teammember.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @teammember }
    end
  end

  # GET /teammembers/new
  # GET /teammembers/new.json
  def new
    @teammember = Teammember.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @teammember }
    end
  end

  # GET /teammembers/1/edit
  def edit
    @teammember = Teammember.find(params[:id])
  end

  # POST /teammembers
  # POST /teammembers.json
  def create
    @teammember = Teammember.new(params[:teammember])

    respond_to do |format|
      if @teammember.save
        format.html { redirect_to @teammember, :notice => 'Teammember was successfully created.' }
        format.json { render :json => @teammember, :status => :created, :location => @teammember }
      else
        format.html { render :action => "new" }
        format.json { render :json => @teammember.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teammembers/1
  # PUT /teammembers/1.json
  def update
    @teammember = Teammember.find(params[:id])

    respond_to do |format|
      if @teammember.update_attributes(params[:teammember])
        format.html { redirect_to @teammember, :notice => 'Teammember was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @teammember.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teammembers/1
  # DELETE /teammembers/1.json
  def destroy
    @teammember = Teammember.find(params[:id])
    @teammember.destroy

    respond_to do |format|
      format.html { redirect_to teammembers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teammembers_helper.rb
module TeammembersHelper
end

app/views/teammembers/_form.html.erb
<%= form_for(@teammember) do |f| %>
  <% if @teammember.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teammember.errors.count, "error") %> prohibited this teammember from being saved:</h2>

      <ul>
      <% @teammember.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idteams %><br />
    <%= f.number_field :idteams %>
  </div>
  <div class="field">
    <%= f.label :idusers %><br />
    <%= f.number_field :idusers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teammembers/edit.html.erb
<h1>Editing teammember</h1>

<%= render 'form' %>

<%= link_to 'Show', @teammember %> |
<%= link_to 'Back', teammembers_path %>

app/views/teammembers/index.html.erb
<h1>Listing teammembers</h1>

<table>
  <tr>
    <th>Idteams</th>
    <th>Idusers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teammembers.each do |teammember| %>
  <tr>
    <td><%= teammember.idteams %></td>
    <td><%= teammember.idusers %></td>
    <td><%= link_to 'Show', teammember %></td>
    <td><%= link_to 'Edit', edit_teammember_path(teammember) %></td>
    <td><%= link_to 'Destroy', teammember, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teammember', new_teammember_path %>

app/views/teammembers/new.html.erb
<h1>New teammember</h1>

<%= render 'form' %>

<%= link_to 'Back', teammembers_path %>

app/views/teammembers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Idteams:</b>
  <%= @teammember.idteams %>
</p>

<p>
  <b>Idusers:</b>
  <%= @teammember.idusers %>
</p>


<%= link_to 'Edit', edit_teammember_path(@teammember) %> |
<%= link_to 'Back', teammembers_path %>