config/routes.rb
Tag::Application.routes.draw do
  get "welcome/1"
  get "welcome/2"
  get "welcome/3"
  get "welcome/4"
  get "welcome/5"
  get "welcome/6"
  get "welcome/7"
  get "welcome/8"
  get "welcome/9"
  get "welcome/10"
  get "welcome/11"
  get "welcome/12"
  get "welcome/studash"
  get "welcome/studash2"

  get "welcome/contact"

  resources :user_game_preferences

  resources :games

  resources :user_funs

  match "/funs/home" => "funs#home" 
  match "/funs/fun_list" => "funs#fun_list" 
  match "/funs/my_fun_list" => "funs#my_fun_list" 
  resources :funs

  resources :music_likes

  match "/musics/music_list" => "musics#music_list"
  resources :musics

  match "/sport_levels/sport_level_list" => "sport_levels#sport_level_list"
  match "/sport_levels/home" => "sport_levels#home"
  match "/sport_levels/guidence" => "sport_levels#guidence"
  match "/sport_levels/video" => "sport_levels#video"
  resources :sport_levels

  resources :scaffolds

  get "/home" => "admin#home"
  get "/tools" => "admin#tools"

  resources :user_sport_preferences

  resources :pe_classmembers

  match "/class" => "pe_classes#home"
  match "/class/news" => "pe_classes#news_list"
  resources :pe_classes

  resources :schools

  resources :teammembers

  match "/teams/home" => "teams#home"
  match "/teams/team_information" => "teams#team_information"
  match "/teams/teamowner_information" => "teams#teamowner_information"
  match "/teams/team_information_list" => "teams#team_information_list"
  match "/teams/score_list" => "teams#score_list"
  resources :teams

  resources :sports

  match "/trainers/home" => "trainers#home"  
  resources :trainers 

  match "/teachers/home" => "teachers#home" 
  match "/teachers/class_list" => "teachers#class_list" 
  match "/teachers/student_list" => "teachers#student_list" 
  match "/teachers/student_information" => "teachers#student_information" 
  match "/teachers/event_list" => "teachers#event_list" 
  resources :teachers

  match "/events/datetime_list" => "events#datetime_list"
  match "/events/event_information" => "events#event_information"
  match "/events/my_event_information" => "events#my_event_information"
  resources :events

  match "/locations/location_list" => "locations#location_list"
  resources :locations

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy

    get 'login_teacher' => :new_teacher
    post 'login_teacher' => :create_teacher
    delete 'logout_teacher' => :destroy_teacher
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :sessions

  match "/users/confirm_information" => "users#confirm_information"
  match "/users/confirm_parental_consent" => "users#confirm_parental_consent"
  match "/users/render_confirm_parental_consent" => "users#render_confirm_parental_consent"
  match "/users/render_reset_password" => "users#render_reset_password"
  match "/users/reset_password" => "users#reset_password"
  resources :users

  root :to => 'welcome#index'

end

app/models/teacher.rb
require 'digest/sha2'

class Teacher < ActiveRecord::Base
  # attr_accessible
  attr_accessible :email, :firstname, :lastname, :gender, :telephone, :password, :password_confirmation

  # dependencies
  belongs_to :school
  has_many :pe_classes

  # email validates: exist, unique
  validates :email, :presence => true, :uniqueness => true

  # password validates: reenter match, exist
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password

  validate :password_must_be_present

  # functions
  # authenticate(email, password)
  #   INPUT: email, password (values)
  #   OUTPUT: teacher (Teacher.object)
  #   FROM: /views/teachers/login
  #   TO: /views/teachers/home
  #   2012.7.10 Yueying
  class << self
    def Teacher.authenticate(email, password)
      if teacher = find_by_email(email)
        $a = encrypt_password(password, teacher.salt)
        if teacher.hashed_password == encrypt_password(password, teacher.salt)[0,30] #!!!
          teacher
        end
      end
    end
    
    # encrypt password
    def encrypt_password(password, salt)
      Digest::SHA2.hexdigest(password + "wibble" + salt)
    end
  end

  # def password (password is a virtual attribute）
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)[0,30] 
    end
  end

  private
    def password_must_be_present
      errors.add(:password, "Missing password" ) unless hashed_password.present?
    end

    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to '/teachers/home', :notice => 'Teacher was successfully created.' }
      else
        format.html { render :action => "new" }
        format.json { render :json => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, :notice => 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  # class_list
  #   INPUT: teacher_id (session value)
  #   OUTPUT: classes (Class.object)
  #   FROM: views/teachers/home
  #   TO: views/teachers/class_list
  #   2012.7.9 Yueying
  def class_list
    @pe_classes = PeClass.find_all_by_teacher_id(session[:teacher_id])
  end

  # student_list
  #   INPUT: pe_class_id (value)
  #   OUTPUT: user (User.object)
  #   FROM: views/teachers/class_list
  #   TO: views/teachers/student_list
  #   2012.7.10 Yueying
  def student_list
    @users = User.find_all_by_pe_class_id(params[:pe_class_id])
  end

  # student_information
  #   INPUT: user_id (value)
  #   OUTPUT: team (Team.object)
  #   FROM: views/teachers/student_list
  #   TO: views/teachers/student_information
  #   2012.7.10 Yueying
  def student_information
team = Team.find_by_user1(params[:user_id])
    @team = Team.find_by_user1(params[:user_id])
teammate = Team.find_teammate(params[:user_id])
debugger
    @teammate = Team.find_teammate(params[:user_id])
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname %><br />

  <%= f.label :lastname %>
  <%= f.text_field :lastname %><br />

  <%= f.label :gender %>
  <%= f.text_field :gender %><br />

  <%= f.label :email %>
  <%= f.text_field :email %><br />

  <%= f.label :telephone %>
  <%= f.text_field :telephone %><br />

  <%= f.label :password, 'Password'%>
  <%= f.password_field :password%><br />
  <%= f.label :password_confirmation, 'Confirm'%>
  <%= f.password_field :password_confirmation%><br />

  <%= f.submit %>
<% end %>

app/views/teachers/class_list.html.erb
<h1>Listing Classes</h1>

  <% @pe_classes.each do |pe_class| %>
    <div><%= pe_class.name %>
    <%= link_to "Listing Students", {:controller => "teachers", :action => "student_list", :pe_class_id => pe_class.id} %>
    <%= link_to "Listing Events", {:controller => "teachers", :action => "event_list", :pe_class_id => pe_class.id} %></div>
  <% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/home.html.erb
<h1>Teacher Home</h1>

    <div>
    <%= link_to "Class List", '/teachers/class_list' %>
    <%= link_to "Class Analysis", '' %>
    <%= link_to "Create Event", '' %>
    <%= link_to "Video List", '' %></div>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Sex</th>
    <th>Email</th>
    <th>Telephone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.firstname %></td>
    <td><%= teacher.lastname %></td>
    <td><%= teacher.sex %></td>
    <td><%= teacher.email %></td>
    <td><%= teacher.telephone %></td>
    <td><%= link_to 'Show', teacher %></td>
    <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
    <td><%= link_to 'Destroy', teacher, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @teacher.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @teacher.lastname %>
</p>

<p>
  <b>Sex:</b>
  <%= @teacher.sex %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>

<p>
  <b>Telephone:</b>
  <%= @teacher.telephone %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/student_information.html.erb
<h1>Student Information</h1>

  <div><%= @team.name %></div>
  <div><%= @teammate.firstname + "." + @teammate.lastname %></div>
  <div><%= @team.event.sport.name %></div>
  <div><%= @team.sport_level.name %></div>

app/views/teachers/student_list.html.erb
<h1>Listing Students</h1>

  <% @users.each do |user| %>
    <div><%= user.firstname + "." + user.lastname %>
    <%= link_to "Information", {:controller => "teachers", :action => "student_information", :user_id => user.id} %></div>
  <% end %>