config/routes.rb
Tag::Application.routes.draw do
  get "welcome/1"
  get "welcome/2"
  get "welcome/3"
  get "welcome/4"
  get "welcome/5"
  get "welcome/6"
  get "welcome/7"
  get "welcome/8"
  get "welcome/9"
  get "welcome/10"
  get "welcome/11"
  get "welcome/12"
  get "welcome/studash"
  get "welcome/studash2"

  get "welcome/contact"

  resources :user_game_preferences

  resources :games

  resources :user_funs

  match "/funs/home" => "funs#home" 
  match "/funs/fun_list" => "funs#fun_list" 
  match "/funs/my_fun_list" => "funs#my_fun_list" 
  resources :funs

  resources :music_likes

  match "/musics/music_list" => "musics#music_list"
  resources :musics

  match "/sport_levels/sport_level_list" => "sport_levels#sport_level_list"
  match "/sport_levels/home" => "sport_levels#home"
  match "/sport_levels/guidence" => "sport_levels#guidence"
  match "/sport_levels/video" => "sport_levels#video"
  resources :sport_levels

  resources :scaffolds

  get "/home" => "admin#home"
  get "/tools" => "admin#tools"

  resources :user_sport_preferences

  resources :pe_classmembers

  match "/class" => "pe_classes#home"
  match "/class/news" => "pe_classes#news_list"
  resources :pe_classes

  resources :schools

  resources :teammembers

  match "/teams/home" => "teams#home"
  match "/teams/team_information" => "teams#team_information"
  match "/teams/teamowner_information" => "teams#teamowner_information"
  match "/teams/team_information_list" => "teams#team_information_list"
  match "/teams/score_list" => "teams#score_list"
  resources :teams

  resources :sports

  match "/trainers/home" => "trainers#home"  
  resources :trainers 

  match "/teachers/home" => "teachers#home" 
  match "/teachers/class_list" => "teachers#class_list" 
  match "/teachers/student_list" => "teachers#student_list" 
  match "/teachers/student_information" => "teachers#student_information" 
  match "/teachers/event_list" => "teachers#event_list" 
  resources :teachers

  match "/events/datetime_list" => "events#datetime_list"
  match "/events/event_information" => "events#event_information"
  match "/events/my_event_information" => "events#my_event_information"
  resources :events

  match "/locations/location_list" => "locations#location_list"
  resources :locations

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy

    get 'login_teacher' => :new_teacher
    post 'login_teacher' => :create_teacher
    delete 'logout_teacher' => :destroy_teacher
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :sessions

  match "/users/confirm_information" => "users#confirm_information"
  match "/users/confirm_parental_consent" => "users#confirm_parental_consent"
  match "/users/render_confirm_parental_consent" => "users#render_confirm_parental_consent"
  match "/users/render_reset_password" => "users#render_reset_password"
  match "/users/reset_password" => "users#reset_password"
  resources :users

  root :to => 'welcome#index'

end

app/models/music.rb
class Music < ActiveRecord::Base
  # attr_accessible
  attr_accessible :artist, :name, :popularity, :user_id

  # dependencies
  belongs_to :user
  has_many :music_likes

  # functions
  # find_musics_by_user(user_id)
  #   INPUT: user_id (value)
  #   OUTPUT: musics (Music.object)
  #   FROM: controllers/musics_controller/music_list
  #   2012.7.3 Yueying
  def self.find_musics_by_user(user_id)
    user = User.find(user_id)
    pe_class_id = user.pe_class_id
    music_ids = Music.find_by_sql("SELECT musics.id FROM users, musics WHERE users.pe_class_id = " + pe_class_id.to_s + " AND users.id = musics.user_id")
    return musics = Music.find_all_by_id(music_ids)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @musics }
    end
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    @music = Music.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @music }
    end
  end

  # GET /musics/new
  # GET /musics/new.json
  def new
    @music = Music.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @music }
    end
    
  end

  # GET /musics/1/edit
  def edit
    music = Music.find(params[:id])
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(params[:music])
    @music.user_id = session[:user_id]
    @music.save

    respond_to do |format|
      if @music.save
        format.html {redirect_to "/admin/home"}
      end
    end
  end

  # PUT /musics/1
  # PUT /musics/1.json
  def update
    @music = Music.find(params[:id])

    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to @music, :notice => 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @music.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music = Music.find(params[:id])
    @music.destroy

    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end

  # music_list
  #   INPUT: user_id (session value)
  #   OUTPUT: SHOW music (Music.object), SAVE music_like
  #   FROM: views/classes/home
  #   TO: views/musics/music_list
  #   2012.7.3 Yueying
  def music_list
    @musics = Music.find_musics_by_user(session[:user_id])
     
    music_like = MusicLike.new
    music_like.user_id = session[:user_id]
    hash = params[:like]
    if  hash != nil
      hash_invert = hash.invert
      music_like.music_id = hash_invert.values_at("like").first.to_i
      music_like.save

      music = music_like.music
      sql = ActiveRecord::Base.connection()
      sql.execute("UPDATE musics SET musics.popularity = musics.popularity + 1 WHERE musics.id = " + music.id.to_s)
    end
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
    <div><%= f.label :name %>
    <%= f.text_field :name %></div></br>
    <div><%= f.label :artist %>
    <%= f.text_field :artist %></div></br>
    <div><%= f.submit %></div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Artist</th>
    <th>Popularity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musics.each do |music| %>
  <tr>
    <td><%= music.name %></td>
    <td><%= music.artist %></td>
    <td><%= music.popularity %></td>
    <td><%= link_to 'Show', music %></td>
    <td><%= link_to 'Edit', edit_music_path(music) %></td>
    <td><%= link_to 'Destroy', music, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Music', new_music_path %>

app/views/musics/music_list.html.erb
<h1>Listing musics</h1>

<%= form_tag('music_list') do %>
  <% @musics.each do |music| %>
    <div><%= music.name %></div>
    <div><%= music.artist %></div>
    <div><%= music.popularity %></div>
    <div><%= submit_tag "like", :name => "like[#{music.id}]" %></div>
  <% end %>
  <div><%= link_to "Recommend Music", '/musics/new' %></div>
<% end %>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form' %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @music.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @music.artist %>
</p>

<p>
  <b>Popularity:</b>
  <%= @music.popularity %>
</p>


<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>